[build]
    bin = "main"
    cmd = "go build -o main main.go"
    dir = "."
    include_ext = ["go"]
    exclude_dir = ["tmp", "client", "node_modules/*, node_modules"]
    include = ["**/*.go"]
    ignore = ["tmp/*", "client/*", "node_modules/*, node_modules"]
    run_after = ["chmod +x main"]

[log]
    level = "debug"

