name: 🧹 ESLint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'client/**'

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install dependencies
        working-directory: client
        run: npm ci

      - name: 🧪 Run ESLint and generate SARIF
        working-directory: client
        run: |
          npx eslint . --config eslint.config.js -f @microsoft/eslint-formatter-sarif -o eslint-results.sarif

      - name: 📤 Upload ESLint analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: client/eslint-results.sarif
